services:

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fizzbuzz"
    environment: # Pass environment variables to the service
      REDIS_URL: "redis:6379"
      REDIS_PASS: ""
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - backend
    ports:
      - "8080:8080"

  redis:
    image: "redis:alpine" # Use a public Redis image to build the db service
    restart: unless-stopped
    container_name: "redis"
    networks:
      - backend

networks:
  backend: